use gleam::gl::Gl;

use crate::call;

macro_rules! match_call {
    {
        ( $gl:expr, $call:expr ):
        $(
            $method:ident { $( $arg:ident ),* $(,)? } => $arm:tt $( ( $( $arm_arg:tt ),* ) ) ?
        ),*
    } => {
        match $call {
            $(
                $method { $( $arg ),* } =>
                    match_call!(@arm ( $gl, $call ) $method ( $( $arg ),* ) => $arm $( ( $( $arm_arg ),* ) ) ?),
            )*
        }
    };

    // 'unimplemented': print an error message and crash.
    { @arm ($gl:expr, $call:expr) $method:ident ( $( $arg:ident ),* ) => unimplemented } => {
        unimplemented!(concat!("gl-replay: replay ", stringify!($method)))
    };

    // 'simple' means: just pass all the arguments through directly.
    { @arm ($gl:expr, $call:expr) $method:ident ( $( $arg:ident ),* ) => simple } => {
        $gl . $method ( $( $arg ),* ),
    };
}

#[allow(unused_variables)]
pub fn replay(gl: &dyn Gl, calls: &[call::Call], variable: &[u8]) {
    for call in calls {
        use call::Call::*;
        match_call! { (gl, call):
            active_texture { texture } => unimplemented,
            bind_buffer { target, buffer } => unimplemented,
            bind_texture { target, texture } => unimplemented,
            bind_vertex_array { vao } => unimplemented,
            buffer_data_untyped {
                target,
                size_data,
                usage,
            } => unimplemented,
            clear_color { r, g, b, a } => unimplemented,
            disable { cap } => unimplemented,
            disable_vertex_attrib_array { index } => unimplemented,
            enable { cap } => unimplemented,
            enable_vertex_attrib_array { index } => unimplemented,
            gen_buffers { n, returned } => unimplemented,
            gen_framebuffers { n, returned } => unimplemented,
            gen_queries { n, returned } => unimplemented,
            gen_renderbuffers { n, returned } => unimplemented,
            gen_textures { n, returned } => unimplemented,
            gen_vertex_arrays { n, returned } => unimplemented,
            gen_vertex_arrays_apple { n, returned } => unimplemented,
            line_width { width } => unimplemented,
            pixel_store_i { name, param } => unimplemented,
            scissor {
                x,
                y,
                width,
                height,
            } => unimplemented,
            tex_image_2d {
                target,
                level,
                internal_format,
                width,
                height,
                border,
                format,
                ty,
                opt_data,
            } => unimplemented,
            tex_image_3d {
                target,
                level,
                internal_format,
                width,
                height,
                depth,
                border,
                format,
                ty,
                opt_data,
            } => unimplemented,
            tex_parameter_f {
                target,
                pname,
                param,
            } => unimplemented,
            tex_parameter_i {
                target,
                pname,
                param,
            } => unimplemented,
            tex_sub_image_3d {
                target,
                level,
                xoffset,
                yoffset,
                zoffset,
                width,
                height,
                depth,
                format,
                ty,
                data,
            } => unimplemented,
            use_program { program } => unimplemented,
            vertex_attrib_divisor { index, divisor } => unimplemented,
            vertex_attrib_i_pointer {
                index,
                size,
                type_,
                stride,
                offset,
            } => unimplemented,
            vertex_attrib_pointer {
                index,
                size,
                type_,
                normalized,
                stride,
                offset,
            } => unimplemented,
            viewport {
                x,
                y,
                width,
                height,
            } => unimplemented,
            bind_vertex_array_apple { vao } => unimplemented,
            bind_renderbuffer {
                target,
                renderbuffer,
            } => unimplemented,
            bind_framebuffer {
                target,
                framebuffer,
            } => unimplemented,
            framebuffer_texture_2d {
                target,
                attachment,
                textarget,
                texture,
                level,
            } => unimplemented,
            framebuffer_texture_layer {
                target,
                attachment,
                texture,
                level,
                layer,
            } => unimplemented,
            blit_framebuffer {
                src_x0,
                src_y0,
                src_x1,
                src_y1,
                dst_x0,
                dst_y0,
                dst_x1,
                dst_y1,
                mask,
                filter,
            } => unimplemented,
            hint {
                param_name,
                param_val,
            } => unimplemented,
            is_enabled { cap } => unimplemented,
            is_shader { shader } => unimplemented,
            is_texture { texture } => unimplemented,
            is_framebuffer { framebuffer } => unimplemented,
            is_renderbuffer { renderbuffer } => unimplemented,
            check_frame_buffer_status { target } => unimplemented,
            renderbuffer_storage {
                target,
                internalformat,
                width,
                height,
            } => unimplemented,
            framebuffer_renderbuffer {
                target,
                attachment,
                renderbuffertarget,
                renderbuffer,
            } => unimplemented,
            tex_sub_image_2d_pbo {
                target,
                level,
                xoffset,
                yoffset,
                width,
                height,
                format,
                ty,
                offset,
            } => unimplemented,
            flush {} => unimplemented,
            finish {} => unimplemented,
            depth_mask { flag } => unimplemented,
            create_program { returned } => unimplemented,
            create_shader {
                shader_type,
                returned,
            } => unimplemented,
            shader_source { shader, strings } => unimplemented,
            compile_shader { shader } => unimplemented,
            get_shader_iv {
                shader,
                pname,
                result,
            } => unimplemented,
            attach_shader { program, shader } => unimplemented,
            bind_attrib_location {
                program,
                index,
                name,
            } => unimplemented,
            link_program { program } => unimplemented,
            delete_shader { shader } => unimplemented,
            detach_shader { program, shader } => unimplemented,
            clear { buffer_mask } => unimplemented,
            clear_depth { depth } => unimplemented,
            clear_stencil { s } => unimplemented,
            get_attrib_location { program, name } => unimplemented,
            get_frag_data_location { program, name } => unimplemented,
            get_uniform_location { program, name } => unimplemented,
            get_program_iv {
                program,
                pname,
                result,
            } => unimplemented,
            uniform_1i { location, v0 } => unimplemented,
            uniform_1iv { location, values } => unimplemented,
            uniform_1f { location, v0 } => unimplemented,
            uniform_1fv { location, values } => unimplemented,
            uniform_1ui { location, v0 } => unimplemented,
            uniform_2f { location, v0, v1 } => unimplemented,
            uniform_2fv { location, values } => unimplemented,
            uniform_2i { location, v0, v1 } => unimplemented,
            uniform_2iv { location, values } => unimplemented,
            uniform_2ui { location, v0, v1 } => unimplemented,
            uniform_3f {
                location,
                v0,
                v1,
                v2,
            } => unimplemented,
            uniform_3fv { location, values } => unimplemented,
            uniform_3i {
                location,
                v0,
                v1,
                v2,
            } => unimplemented,
            uniform_3iv { location, values } => unimplemented,
            uniform_3ui {
                location,
                v0,
                v1,
                v2,
            } => unimplemented,
            uniform_4f {
                location,
                x,
                y,
                z,
                w,
            } => unimplemented,
            uniform_4i {
                location,
                x,
                y,
                z,
                w,
            } => unimplemented,
            uniform_4iv { location, values } => unimplemented,
            uniform_4ui {
                location,
                x,
                y,
                z,
                w,
            } => unimplemented,
            uniform_4fv { location, values } => unimplemented,
            uniform_matrix_2fv {
                location,
                transpose,
                value,
            } => unimplemented,
            uniform_matrix_3fv {
                location,
                transpose,
                value,
            } => unimplemented,
            uniform_matrix_4fv {
                location,
                transpose,
                value,
            } => unimplemented,
            depth_range { near, far } => unimplemented,
            draw_elements_instanced {
                mode,
                count,
                element_type,
                indices_offset,
                primcount,
            } => unimplemented,
            blend_color { r, g, b, a } => unimplemented,
            blend_func { sfactor, dfactor } => unimplemented,
            blend_func_separate {
                src_rgb,
                dest_rgb,
                src_alpha,
                dest_alpha,
            } => unimplemented,
            blend_equation { mode } => unimplemented,
            blend_equation_separate {
                mode_rgb,
                mode_alpha,
            } => unimplemented,
            color_mask { r, g, b, a } => unimplemented,
            cull_face { mode } => unimplemented,
            front_face { mode } => unimplemented,
            depth_func { func } => unimplemented,
            invalidate_framebuffer {
                target,
                attachments,
            } => unimplemented,
            invalidate_sub_framebuffer {
                target,
                attachments,
                xoffset,
                yoffset,
                width,
                height,
            } => unimplemented,
            read_buffer { mode } => unimplemented,
            read_pixels_into_buffer {
                x,
                y,
                width,
                height,
                format,
                pixel_type,
                dst_buffer,
            } => unimplemented,
            read_pixels {
                x,
                y,
                width,
                height,
                format,
                pixel_type,
            } => unimplemented,
            read_pixels_into_pbo {
                x,
                y,
                width,
                height,
                format,
                pixel_type,
            } => unimplemented,
            sample_coverage { value, invert } => unimplemented,
            polygon_offset { factor, units } => unimplemented,
            begin_query { target, id } => unimplemented,
            end_query { target } => unimplemented,
            query_counter { id, target } => unimplemented,
            get_query_object_iv {
                id,
                pname,
                returned,
            } => unimplemented,
            get_query_object_uiv {
                id,
                pname,
                returned,
            } => unimplemented,
            get_query_object_i64v {
                id,
                pname,
                returned,
            } => unimplemented,
            get_query_object_ui64v {
                id,
                pname,
                returned,
            } => unimplemented,
            delete_queries { queries } => unimplemented,
            delete_vertex_arrays { vertex_arrays } => unimplemented,
            delete_vertex_arrays_apple { vertex_arrays } => unimplemented,
            delete_buffers { buffers } => unimplemented,
            delete_renderbuffers { renderbuffers } => unimplemented,
            delete_framebuffers { framebuffers } => unimplemented,
            delete_textures { textures } => unimplemented,
            delete_program { program } => unimplemented,
            tex_sub_image_3d_pbo {
                target,
                level,
                xoffset,
                yoffset,
                zoffset,
                width,
                height,
                depth,
                format,
                ty,
                offset,
            } => unimplemented,
            tex_storage_2d {
                target,
                levels,
                internal_format,
                width,
                height,
            } => unimplemented,
            tex_storage_3d {
                target,
                levels,
                internal_format,
                width,
                height,
                depth,
            } => unimplemented,
            get_tex_image_into_buffer {
                target,
                level,
                format,
                ty,
                output,
            } => unimplemented,
            copy_image_sub_data {
                src_name,
                src_target,
                src_level,
                src_x,
                src_y,
                src_z,
                dst_name,
                dst_target,
                dst_level,
                dst_x,
                dst_y,
                dst_z,
                src_width,
                src_height,
                src_depth,
            } => unimplemented,
            generate_mipmap { target } => unimplemented
        }
    }
}
